apiVersion: v1
kind: Service
metadata:
  name: election-controller
spec:
  selector:
    app: election-controller
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP