apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-controller
  labels:
    app: election-controller
spec:
    replicas: 1
    selector:
        matchLabels:
          app: election-controller
    template:
      metadata:
        labels:
          app: election-controller
      spec:
        containers:
          - name: controller
            image: luccarhaddad/election-controller:latest
            ports:
              - containerPort: 50051
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
