apiVersion: apps/v1
kind: Deployment
metadata:
  name: election-worker
  labels:
    app: election-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: election-worker
  template:
    metadata:
      labels:
        app: election-worker
    spec:
      containers:
        - name: worker
          image: luccarhaddad/election-worker:latest
          ports:
            - containerPort: 50052
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: CONTROLLER_ADDRESS
              value: "election-controller.default.svc.cluster.local:50051"