FROM --platform=$BUILDPLATFORM golang:1.22.6 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o worker ./cmd/worker

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/worker .

CMD ["./worker"]